### ISSUE TITLE
Error message on install

### ISSUE THREAD

**Issue by undulat** [LassoSoft/Lasso-HTML.mode#1]
Hi,

after double-clicking on the module to have it installed in Coda 2.5, Coda shows the error message as shown here.
![screen shot 2015-06-08 at 13 56 29](https://cloud.githubusercontent.com/assets/8578785/8034284/8f462ef8-0de6-11e5-95fe-115cd264062a.png)

**Comment by EricFromCanada** [comment]
Are you using the most recent version? It should have a purple icon. If double-clicking Lasso-HTML.mode still fails to install it, manually remove the old version from `~/Library/Application Support/Coda 2/Modes` and quit Coda before trying again.
