### ISSUE TITLE
Error in Coda 2.5.17 after upgrade to macOS Sierra 10.12

### ISSUE THREAD

**Issue by maxwellk2** [LassoSoft/Lasso-HTML.mode#2]
With the "Lasso-HTML 1.0" Mode activated an "Internal Error" dialog is triggered regularly. Details begin with...

   Exception Name: RKLICURegexException

When Mode is disabled error goes away.

**Comment by EricFromCanada** [comment]
The error name points to RegexKitLite, a library which makes available the regex engine in OS X's ICU. A quick comparison of Coda 2.5.17 running on 10.11 and 10.12 suggests that there have been changes in its ICU libraries that Coda isn't handling, e.g. Lasso library files (no delimiters) aren't being highlighted correctly. Do you have a specific file snippet that appears to bring about the error?

**Comment by maxwellk2** [comment]
Hi Eric. The crash seems to happen with just about any code, even just one line, both Lasso 8 and Lasso 9 projects (though Lasso 9 code appears to crash Coda less often), using square brackets or "<?lasso ?>", with or without ";" line endings - can't find a pattern. And it seems random when a crash will occur. Clicking "Continue" in the "Internal Error" dialog a given page will be fine to work on, edits, saves, jumping to and from other pages - all good - but then out of the blue the crash dialog will appear.

Appreciate your investigation and happy to provide any other information or testing that might help. The built-in LassoScript-HTML seems workable for the time being.
